#!/bin/bash
# script to create HaitiOS-lite -- without 21020O.img and wikipediafr*.xo
set -x -e -u
VERSION=`git describe | sed 's/^v//' | sed 's/-/./g'`
if [ $# -gt 0 ] && [ "$1" == "full" ]; then
	tar zcfv ../HaitiOS-$VERSION.tar.gz *
else
	tar zcfv ../HaitiOS-$VERSION.tar.gz -X exclude_list *
fi

